baseURL = "nvedant.github.io"
languageCode = "en-us"
title = "vedant"

[params.author]
name = "Vedant Nandwana"

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = true
    style = 'algol_nu'
    tabWidth = 4
    

