baseURL = "nvedant.github.io"
languageCode = "en-us"
title = "vedant"
disableKinds = ["taxonomy", "term"]

[params]
  images = ['cover.png']
  title = 'vedant'
  [params.author]
     name = "vedant nandwana"

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = true
    style = "algol_nu"
    tabWidth = 4
    

